import type { Product, Collection, BlogPost } from './types';

export const products: Product[] = [
  {
    id: '1',
    slug: 'the-minimalist-tee',
    name: 'The Minimalist Tee',
    price: 45.00,
    imageIds: ['product-1-1', 'product-1-2', 'product-1-3'],
    description: 'A flawless essential, our Minimalist Tee is crafted from premium Pima cotton for a soft, breathable feel. Its classic crewneck and relaxed fit make it a versatile foundation for any outfit.',
    category: 'Essentials',
    tags: ['New Arrival', 'Best Seller'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Off-White', hex: '#FAFAF9' },
      { name: 'Soft Grey', hex: '#D1D5DB' },
      { name: 'Black', hex: '#111827' },
    ],
    rating: 4.9,
    reviewCount: 124,
    details: [
      '100% Peruvian Pima cotton',
      'Slightly relaxed fit',
      'Machine wash cold, tumble dry low',
      'Sustainably sourced',
    ],
    stock: 100,
    affiliateUrl: 'https://example.com/product/minimalist-tee',
  },
  {
    id: '2',
    slug: 'city-chic-trench-coat',
    name: 'City-Chic Trench Coat',
    price: 220.00,
    imageIds: ['product-2-1', 'product-2-2', 'product-2-3'],
    description: 'The quintessential outerwear piece, updated for the modern wardrobe. Our City-Chic Trench features a water-resistant cotton blend, classic double-breasted closure, and a removable belt for a customized silhouette.',
    category: 'Womens',
    tags: ['Featured'],
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Beige', hex: '#D5C5B6' },
    ],
    rating: 4.8,
    reviewCount: 88,
    details: [
      '65% Cotton, 35% Polyester',
      'Water-resistant finish',
      'Deep side pockets',
      'Dry clean only',
    ],
    stock: 30,
    affiliateUrl: 'https://example.com/product/city-chic-trench-coat',
  },
  {
    id: '3',
    slug: 'tailored-linen-trousers',
    name: 'Tailored Linen Trousers',
    price: 130.00,
    imageIds: ['product-3-1', 'product-3-2', 'product-3-3'],
    description: 'Breatheable and effortlessly elegant, these trousers are your new warm-weather staple. Made from a high-quality linen blend, they feature a flattering high-waist and wide-leg cut.',
    category: 'Womens',
    tags: ['New Arrival'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Off-White', hex: '#FAFAF9' },
      { name: 'Beige', hex: '#D5C5B6' },
    ],
    rating: 4.7,
    reviewCount: 56,
    details: [
      '70% Linen, 30% Viscose',
      'High-waisted, wide-leg fit',
      'Zip fly with hook-and-bar closure',
      'Hand wash or machine wash delicate',
    ],
    stock: 60,
    affiliateUrl: 'https://example.com/product/tailored-linen-trousers',
  },
  {
    id: '4',
    slug: 'effortless-silk-blouse',
    name: 'Effortless Silk Blouse',
    price: 160.00,
    imageIds: ['product-4-1', 'product-4-2', 'product-4-3'],
    description: 'The epitome of quiet luxury. Our Effortless Silk Blouse is made from 100% Mulberry silk, offering a fluid drape and a subtle sheen. A timeless piece for work or evening.',
    category: 'Womens',
    tags: ['Featured', 'Best Seller'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Off-White', hex: '#FAFAF9' },
      { name: 'Burgundy', hex: '#800020' },
    ],
    rating: 4.9,
    reviewCount: 92,
    details: [
      '100% 19mm Mulberry silk',
      'Concealed button placket',
      'Buttoned cuffs',
      'Dry clean recommended',
    ],
    stock: 45,
    affiliateUrl: 'https://example.com/product/effortless-silk-blouse',
  },
  {
    id: '5',
    slug: 'modernist-wool-sweater',
    name: 'Modernist Wool Sweater',
    price: 180.00,
    imageIds: ['product-5-1', 'product-5-2', 'product-5-3'],
    description: 'A cozy yet sophisticated sweater crafted from responsibly sourced merino wool. The Modernist Sweater has a relaxed fit, a classic crew neck, and ribbed detailing for added texture.',
    category: 'Mens',
    tags: ['Featured'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Soft Grey', hex: '#D1D5DB' },
      { name: 'Deep Burgundy', hex: '#800020' },
    ],
    rating: 4.8,
    reviewCount: 75,
    details: [
      '100% RWS certified Merino wool',
      'Relaxed fit',
      'Ribbed collar, cuffs, and hem',
      'Hand wash cold, lay flat to dry',
    ],
    stock: 50,
    affiliateUrl: 'https://example.com/product/modernist-wool-sweater',
  },
  {
    id: '6',
    slug: 'versatile-denim-jacket',
    name: 'Versatile Denim Jacket',
    price: 150.00,
    imageIds: ['product-6-1', 'product-6-2', 'product-6-3'],
    description: 'An iconic style, perfected. Our denim jacket is made from organic cotton with a hint of stretch for comfort. The timeless wash and clean hardware make it an all-season layer.',
    category: 'Essentials',
    tags: [],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Classic Wash', hex: '#6085A6' },
    ],
    rating: 4.7,
    reviewCount: 110,
    details: [
      '98% Organic Cotton, 2% Elastane',
      'Classic fit',
      'Branded hardware',
      'Machine wash cold',
    ],
    stock: 80,
    affiliateUrl: 'https://example.com/product/versatile-denim-jacket',
  },
   {
    id: '7',
    slug: 'flowy-maxi-dress',
    name: 'Flowy Maxi Dress',
    price: 190.00,
    imageIds: ['product-7-1', 'product-7-2', 'product-7-3'],
    description: 'A statement piece for any special occasion. This maxi dress features a flattering V-neck, an adjustable waist tie, and a tiered skirt that moves beautifully with every step.',
    category: 'Womens',
    tags: ['New Arrival'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Deep Burgundy', hex: '#800020' },
    ],
    rating: 4.9,
    reviewCount: 45,
    details: [
      '100% Tencel™ Lyocell',
      'V-neckline and flutter sleeves',
      'Adjustable waist tie',
      'Machine wash cold on delicate cycle',
    ],
    stock: 25,
    affiliateUrl: 'https://example.com/product/flowy-maxi-dress',
  },
  {
    id: '8',
    slug: 'classic-oxford-shirt',
    name: 'Classic Oxford Shirt',
    price: 95.00,
    imageIds: ['product-8-1', 'product-8-2', 'product-8-3'],
    description: 'The cornerstone of a well-dressed man\'s wardrobe. Our Oxford shirt is cut from durable, soft cotton and tailored for a perfect fit that is neither too slim nor too loose.',
    category: 'Mens',
    tags: ['Best Seller'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Off-White', hex: '#FAFAF9' },
      { name: 'Soft Grey', hex: '#D1D5DB' },
    ],
    rating: 4.8,
    reviewCount: 210,
    details: [
      '100% Organic Cotton Oxford',
      'Button-down collar',
      'Chest pocket',
      'Machine wash warm',
    ],
    stock: 150,
    affiliateUrl: 'https://example.com/product/classic-oxford-shirt',
  },
];

export const collections: Collection[] = [
  {
    id: '1',
    title: "Women's Collection",
    href: '/shop?category=Womens',
    imageId: 'collection-women',
  },
  {
    id: '2',
    title: "Men's Collection",
    href: '/shop?category=Mens',
    imageId: 'collection-men',
  },
  {
    id: '3',
    title: 'The Essentials',
    href: '/shop?category=Essentials',
    imageId: 'collection-essentials',
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: 'building-your-capsule-wardrobe',
    title: 'Building Your Capsule Wardrobe: A Guide to Mindful Fashion',
    author: 'Eleanor Vance',
    date: 'May 15, 2024',
    imageId: 'blog-1',
    excerpt: 'Simplify your life and refine your style with a capsule wardrobe. Learn how to select timeless, versatile pieces that you\'ll love for years to come.',
    content: '<p>In a world of fleeting trends, the concept of a capsule wardrobe offers a refreshing, sustainable alternative. It\'s about curating a collection of essential items that don\'t go out of style, which can then be augmented with seasonal pieces. The goal is to have an outfit suitable for any occasion without owning excessive items of clothing. This approach not only saves time and money but also reduces fashion waste.</p><p>Start by assessing your current wardrobe. What do you love? What do you actually wear? Be ruthless. A good capsule wardrobe is built on high-quality, versatile basics. Think neutral colors: black, white, grey, navy, and camel. For Aptly Dressed, our core palette of off-white, soft grey, and beige is the perfect starting point.</p><p>A classic white tee, a tailored blazer, a perfect-fitting pair of jeans, a little black dress, and a timeless trench coat are all excellent foundations. From there, you can inject personality with accent colors—like our signature deep burgundy—and accessories. The key is that every piece should be able to be mixed and matched with multiple other items in your wardrobe.</p>'
  },
  {
    slug: 'the-art-of-layering',
    title: 'The Art of Layering: Transitional Pieces for Every Season',
    author: 'Julian Finch',
    date: 'June 02, 2024',
    imageId: 'blog-2',
    excerpt: 'Master the art of layering to create stylish, adaptable outfits that can take you from a chilly morning to a warm afternoon. We break down the key pieces.',
    content: '<p>Layering is more than just piling on clothes; it\'s a stylistic art form that adds depth, texture, and versatility to your look. It\'s particularly useful during transitional seasons when the weather is unpredictable. The secret to successful layering is to work with thin layers and different textures.</p><p>Start with a quality base layer, like our Minimalist Tee in Pima cotton. It\'s breathable and soft against the skin. Next, add a middle layer for warmth and style. A piece like our Classic Oxford Shirt or Modernist Wool Sweater works perfectly. The final layer is your outerwear, which protects you from the elements. Our City-Chic Trench Coat is an ideal choice, as it\'s both stylish and functional.</p><p>Don\'t be afraid to play with lengths and textures. A silk blouse under a wool sweater, or a denim jacket over a maxi dress, creates visual interest. The key is to ensure each layer can stand on its own, so you can add or remove pieces as the temperature changes throughout the day.</p>'
  }
];
